/**
 * 全部 Faker 方法路径联合类型（统一格式）
 * 格式：| 'module.methodName'
 * 适用于字符串路径匹配、类型安全调用等场景
 */

type MethodPath =
  // Airline Module
  | 'airline.aircraftType'
  | 'airline.airline'
  | 'airline.airplane'
  | 'airline.airport'
  | 'airline.flightNumber'
  | 'airline.recordLocator'
  | 'airline.seat'

  // Animal Module
  | 'animal.bear'
  | 'animal.bird'
  | 'animal.cat'
  | 'animal.cetacean'
  | 'animal.cow'
  | 'animal.crocodilia'
  | 'animal.dog'
  | 'animal.fish'
  | 'animal.horse'
  | 'animal.insect'
  | 'animal.lion'
  | 'animal.petName'
  | 'animal.rabbit'
  | 'animal.rodent'
  | 'animal.snake'
  | 'animal.type'

  // Book Module
  | 'book.author'
  | 'book.format'
  | 'book.genre'
  | 'book.publisher'
  | 'book.series'
  | 'book.title'

  // Color Module
  | 'color.cmyk'
  | 'color.colorByCSSColorSpace'
  | 'color.cssSupportedFunction'
  | 'color.cssSupportedSpace'
  | 'color.hsl'
  | 'color.human'
  | 'color.hwb'
  | 'color.lab'
  | 'color.lch'
  | 'color.rgb'
  | 'color.space'

  // Commerce Module
  | 'commerce.department'
  | 'commerce.isbn'
  | 'commerce.price'
  | 'commerce.product'
  | 'commerce.productAdjective'
  | 'commerce.productDescription'
  | 'commerce.productMaterial'
  | 'commerce.productName'

  // Company Module
  | 'company.buzzAdjective'
  | 'company.buzzNoun'
  | 'company.buzzPhrase'
  | 'company.buzzVerb'
  | 'company.catchPhrase'
  | 'company.catchPhraseAdjective'
  | 'company.catchPhraseDescriptor'
  | 'company.catchPhraseNoun'
  | 'company.name'

  // Database Module
  | 'database.collation'
  | 'database.column'
  | 'database.engine'
  | 'database.mongodbObjectId'
  | 'database.type'

  // DataType
  | 'datatype.boolean'

  // Date Module
  | 'date.anytime'
  | 'date.between'
  | 'date.betweens'
  | 'date.birthdate'
  | 'date.future'
  | 'date.month'
  | 'date.past'
  | 'date.recent'
  | 'date.soon'
  | 'date.timeZone'
  | 'date.weekday'

  // Finance Module
  | 'finance.accountName'
  | 'finance.accountNumber'
  | 'finance.amount'
  | 'finance.bic'
  | 'finance.bitcoinAddress'
  | 'finance.creditCardCVV'
  | 'finance.creditCardIssuer'
  | 'finance.creditCardNumber'
  | 'finance.currency'
  | 'finance.currencyCode'
  | 'finance.currencyName'
  | 'finance.currencyNumericCode'
  | 'finance.currencySymbol'
  | 'finance.ethereumAddress'
  | 'finance.iban'
  | 'finance.litecoinAddress'
  | 'finance.pin'
  | 'finance.routingNumber'
  | 'finance.transactionDescription'
  | 'finance.transactionType'

  // Food Module
  | 'food.adjective'
  | 'food.description'
  | 'food.dish'
  | 'food.ethnicCategory'
  | 'food.fruit'
  | 'food.ingredient'
  | 'food.meat'
  | 'food.spice'
  | 'food.vegetable'

  // Git Module
  | 'git.branch'
  | 'git.commitDate'
  | 'git.commitEntry'
  | 'git.commitMessage'
  | 'git.commitSha'

  // Hacker Module
  | 'hacker.abbreviation'
  | 'hacker.adjective'
  | 'hacker.ingverb'
  | 'hacker.noun'
  | 'hacker.phrase'
  | 'hacker.verb'

  // Helpers Module
  | 'helpers.arrayElement'
  | 'helpers.arrayElements'
  | 'helpers.enumValue'
  | 'helpers.fake'
  | 'helpers.fromRegExp'
  | 'helpers.maybe'
  | 'helpers.multiple'
  | 'helpers.mustache'
  | 'helpers.objectEntry'
  | 'helpers.objectKey'
  | 'helpers.objectValue'
  | 'helpers.rangeToNumber'
  | 'helpers.replaceCreditCardSymbols'
  | 'helpers.replaceSymbols'
  | 'helpers.shuffle'
  | 'helpers.slugify'
  | 'helpers.uniqueArray'
  | 'helpers.weightedArrayElement'

  // Image Module
  | 'image.avatar'
  | 'image.avatarGitHub'
  | 'image.dataUri'
  | 'image.personPortrait'
  | 'image.url'
  | 'image.urlLoremFlickr'
  | 'image.urlPicsumPhotos'

  // Internet Module
  | 'internet.displayName'
  | 'internet.domainName'
  | 'internet.domainSuffix'
  | 'internet.domainWord'
  | 'internet.email'
  | 'internet.emoji'
  | 'internet.exampleEmail'
  | 'internet.httpMethod'
  | 'internet.httpStatusCode'
  | 'internet.ip'
  | 'internet.ipv4'
  | 'internet.ipv6'
  | 'internet.jwt'
  | 'internet.jwtAlgorithm'
  | 'internet.mac'
  | 'internet.password'
  | 'internet.port'
  | 'internet.protocol'
  | 'internet.url'
  | 'internet.userAgent'
  | 'internet.username'

  // Location Module
  | 'location.buildingNumber'
  | 'location.cardinalDirection'
  | 'location.city'
  | 'location.continent'
  | 'location.country'
  | 'location.countryCode'
  | 'location.county'
  | 'location.direction'
  | 'location.language'
  | 'location.latitude'
  | 'location.longitude'
  | 'location.nearbyGPSCoordinate'
  | 'location.ordinalDirection'
  | 'location.secondaryAddress'
  | 'location.state'
  | 'location.street'
  | 'location.streetAddress'
  | 'location.timeZone'
  | 'location.zipCode'

  // Lorem Module
  | 'lorem.lines'
  | 'lorem.paragraph'
  | 'lorem.paragraphs'
  | 'lorem.sentence'
  | 'lorem.sentences'
  | 'lorem.slug'
  | 'lorem.text'
  | 'lorem.word'
  | 'lorem.words'

  // Music Module
  | 'music.album'
  | 'music.artist'
  | 'music.genre'
  | 'music.songName'

  // Number Module
  | 'number.bigInt'
  | 'number.binary'
  | 'number.boolean'
  | 'number.float'
  | 'number.hex'
  | 'number.int'
  | 'number.octal'
  | 'number.romanNumeral'

  // Person Module
  | 'person.bio'
  | 'person.firstName'
  | 'person.fullName'
  | 'person.gender'
  | 'person.jobArea'
  | 'person.jobDescriptor'
  | 'person.jobTitle'
  | 'person.jobType'
  | 'person.lastName'
  | 'person.middleName'
  | 'person.prefix'
  | 'person.sex'
  | 'person.sexType'
  | 'person.suffix'
  | 'person.zodiacSign'

  // Phone Module
  | 'phone.imei'
  | 'phone.number'

  // Science Module
  | 'science.chemicalElement'
  | 'science.unit'

  // String Module
  | 'string.alpha'
  | 'string.alphanumeric'
  | 'string.binary'
  | 'string.fromCharacters'
  | 'string.hexadecimal'
  | 'string.nanoid'
  | 'string.numeric'
  | 'string.octal'
  | 'string.sample'
  | 'string.symbol'
  | 'string.ulid'
  | 'string.uuid'

  // System Module
  | 'system.commonFileExt'
  | 'system.commonFileName'
  | 'system.commonFileType'
  | 'system.cron'
  | 'system.directoryPath'
  | 'system.fileExt'
  | 'system.fileName'
  | 'system.filePath'
  | 'system.fileType'
  | 'system.mimeType'
  | 'system.networkInterface'
  | 'system.semver'
  | 'vehicle.bicycle'
  | 'vehicle.color'
  | 'vehicle.fuel'
  | 'vehicle.manufacturer'
  | 'vehicle.model'
  | 'vehicle.type'
  | 'vehicle.vehicle'
  | 'vehicle.vin'
  | 'vehicle.vrm'

  // Word Module
  | 'word.adjective'
  | 'word.adverb'
  | 'word.conjunction'
  | 'word.interjection'
  | 'word.noun'
  | 'word.preposition'
  | 'word.sample'
  | 'word.verb'
  | 'word.words';
